# Generated by Django 5.2.7 on 2025-10-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_globalsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalsettings',
            options={},
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='id',
            field=models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
